version: '2'

services:
  elasticsearch:
    build: elasticsearch/
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      # disable X-Pack
      # see https://www.elastic.co/guide/en/x-pack/current/xpack-settings.html
      #     https://www.elastic.co/guide/en/x-pack/current/installing-xpack.html#xpack-enabling
      xpack.security.enabled: "false"
      xpack.monitoring.enabled: "false"
      xpack.graph.enabled: "false"
      xpack.watcher.enabled: "false"
    networks:
      - docker_elk
  logstash:
    build: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "12201:12201/udp"
    networks:
      - docker_elk
    depends_on:
      - elasticsearch
    environment:
      LS_JAVA_OPTS: "-Xms512m -Xmx512m"
  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    networks:
      - docker_elk
    depends_on:
      - elasticsearch
  nginx:
    build: nginx/
    volumes:
      - ./nginx/nginx.conf/:/etc/nginx/nginx.conf
      - ./nginx/certs/:/certs:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
    ports:
      - "443:443"
      - "80:80"
    networks:
      - docker_elk
    depends_on:
      - kibana

networks:
  docker_elk:
    driver: bridge
